name: Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: docker pull ddnirvana/cselab_env:latest
      - name: Test
        run: |
          sudo docker run -it --privileged --cap-add=ALL -v ${PWD}/yfs:/labenv ddnirvana/cselab_env:latest bash -c "cd /labenv && make && ./grade.sh"
