name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: sudo apt-get install libfuse-dev
      - name: Build
        run: make -j
      - name: Test YFS
        continue-on-error: true
        run: ./grade_lab2.sh
      - name: special test for lab2-part1-b
        continue-on-error: true
        shell: bash {0}
        run: |
          ./start.sh && ./test-lab2-part1-b.pl ./yfs1; ./stop.sh \
          cat yfs_client1.log
          cat extent_server.log
