name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo apt-get install libfuse-dev
          git clone https://github.com/sslab-gatech/fxmark.git && cd fxmark && make -j
      - name: Build
        run: make -j lab lab3
      - name: Test YFS
        continue-on-error: true
        run: ./grade_lab2.sh
      - name: special test for lab2-part1-b
        continue-on-error: true
        run: ./start.sh && ./test-lab2-part1-b.pl ./yfs1; ./stop.sh \
          cat yfs_client1.log
          cat extent_server.log
      - name: Test YDB
        continue-on-error: true
        run: make lab3 && ./grade_lab3.sh
