name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: sudo apt-get install libfuse-dev
      - name: Build
        run: make -j
      - name: Test Lock
        run: ./grade_lab2.sh
      - name: Test YDB
        run: ./grade_lab3.sh
